"""The allow-listed output model for `get_job_feed` (DESIGN.md:192-195).

**The third name for one concept, normalised here** (DESIGN.md §9
hazard 3: *"v2 jobs key on `requisitions`, the v1 feed on `jobs`, the
create response nests under `application`"*). `JOB_FEED_ENVELOPE_KEY`
records what Jobvite sends on this route and is read in exactly one
place; the model this unit hands the caller carries a `jobs` list, the
same attribute `JobSearchResult` carries, so a model calling both tools
sees **one** name for the concept and never Jobvite's three. The
normalisation is a rename at the boundary, not a second vocabulary: the
Jobvite key survives in each field's `Fenced` decision, which is the
key space DESIGN.md:202-205 keeps separate on purpose.

**A separate model rather than reusing `Job`, and the difference is not
cosmetic.** The v1 feed and the v2 `/job` route are the same domain
object with **different fields**: the feed sends `id` where v2 sends
`eId`, one `location` STRING where v2 sends a `locations` array of
objects, a `date` string where v2 sends epoch milliseconds in
`lastUpdatedDate`, and `briefdescription`, `jobtype`, `requisitionid`
and `hiringManager`, which v2 does not send at all
(`JOBVITE-CONTRACT.md` §9 and its `jobfeed_success.json` fixture).
Mapping the feed onto `Job` would mean either dropping five fields or
inventing values for three, and both are silent.

**Public job data, and the separate credential class does not change
that** (DESIGN.md:137, DESIGN.md:320-321). What makes this route
special is the CREDENTIAL - it travels in the query string, so the URL
is sensitive - not the payload, which is the career-site feed and is
public by construction. So every field takes the same "not free text"
decision `models/jobs.py` records, for the same reason: it is authored
inside the operator organisation or generated by Jobvite, never by
someone outside it.

**Dates are carried through as Jobvite sent them.** The feed's `date`
is a string on this route rather than the epoch milliseconds v2
returns, which is §9 hazard 2's asymmetry seen from the other side.
`utils/normalise.py` is U8's file and is where a conversion belongs;
declaring the field as what Jobvite actually sends is what keeps this
model honest about which end of the asymmetry it is on.
"""

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, computed_field

from .fencing import Fenced, FencingDecision

#: The v1 feed's collection key - **the third name for one concept**
#: (DESIGN.md §9 hazard 3, `JOBVITE-CONTRACT.md` §9). Read in one place
#: (`tools/jobs.py:build_feed_result`) and normalised to `jobs` on the
#: model below. It is a named constant for the same reason
#: `JOBS_ENVELOPE_KEY` is: a string literal at the read site is what
#: lets a second, disagreeing spelling appear somewhere else.
JOB_FEED_ENVELOPE_KEY = "jobs"

_NOT_FREE_TEXT = FencingDecision.NOT_FREE_TEXT


class FeedJob(BaseModel):
    """One job from the v1 career-site feed, allow-listed.

    The field set is the one `jobfeed_success.json` carries, which is
    the fixture `JOBVITE-CONTRACT.md` §11 provides for this route. A
    key Jobvite adds later is **dropped**, not raised on
    (DESIGN.md:192-195) - `_to_feed_job` names each key, exactly as
    `_to_job` does, rather than handing the raw object to a model whose
    `extra="forbid"` would take the whole call down on a Jobvite
    schema change.
    """

    model_config = ConfigDict(extra="forbid", strict=True)

    eid: Annotated[
        str,
        Fenced(
            _NOT_FREE_TEXT, "id", "opaque Jobvite job id; `id` on this route, not `eId`"
        ),
    ]
    title: Annotated[
        str,
        Fenced(
            _NOT_FREE_TEXT, "title", "requisition title, authored in the operator org"
        ),
    ]
    requisition_id: Annotated[
        str | None,
        Fenced(
            _NOT_FREE_TEXT,
            "requisitionid",
            "operator-facing requisition number, generated by Jobvite",
        ),
    ] = None
    category: Annotated[
        str | None,
        Fenced(_NOT_FREE_TEXT, "category", "career-site category, configured in Admin"),
    ] = None
    job_type: Annotated[
        str | None,
        Fenced(
            _NOT_FREE_TEXT,
            "jobtype",
            "enumerated employment type from Jobvite's own taxonomy",
        ),
    ] = None
    location: Annotated[
        str | None,
        Fenced(
            _NOT_FREE_TEXT,
            "location",
            "place name from Jobvite; ONE string here where v2 sends an array",
        ),
    ] = None
    date: Annotated[
        str | None,
        Fenced(
            _NOT_FREE_TEXT,
            "date",
            "posting date as Jobvite sent it; a string on this route, epoch ms on v2",
        ),
    ] = None
    detail_url: Annotated[
        str | None,
        Fenced(
            _NOT_FREE_TEXT, "detail-url", "URL minted by Jobvite, not typed by anyone"
        ),
    ] = None
    apply_url: Annotated[
        str | None,
        Fenced(
            _NOT_FREE_TEXT, "apply-url", "URL minted by Jobvite, not typed by anyone"
        ),
    ] = None
    brief_description: Annotated[
        str | None,
        Fenced(
            _NOT_FREE_TEXT,
            "briefdescription",
            "recruiter-authored summary; inside the operator org, so not the "
            "attacker-authored class of DESIGN.md:738-744",
        ),
    ] = None
    description: Annotated[
        str | None,
        Fenced(
            _NOT_FREE_TEXT,
            "description",
            "recruiter-authored posting body; inside the operator org, so not the "
            "attacker-authored class of DESIGN.md:738-744",
        ),
    ] = None
    hiring_manager: Annotated[
        str | None,
        Fenced(
            _NOT_FREE_TEXT,
            "hiringManager",
            "an employee name from the operator org, not candidate-supplied",
        ),
    ] = None


class JobFeedResult(BaseModel):
    """One capped page of the job feed, with the cap reported.

    Deliberately the same shape as `JobSearchResult` - `jobs`, `total`,
    `showing`, `summary` - because the two tools return the same
    concept and a caller should not have to learn two envelopes to read
    one domain object. `request_id` is **not** a field here for the
    reason `JobSearchResult` records: `_meta` is the protocol's own
    channel and an undeclared top-level key is rejected outright
    (DESIGN.md:629-637).
    """

    model_config = ConfigDict(extra="forbid", strict=True)

    jobs: Annotated[
        list[FeedJob],
        Fenced(
            _NOT_FREE_TEXT,
            JOB_FEED_ENVELOPE_KEY,
            "container; each element decides",
        ),
    ] = Field(default_factory=list)

    #: Jobvite's own reported total, from the envelope. **Reported,
    #: never trusted as a loop condition** (DESIGN.md:487-489).
    total: Annotated[int, Fenced(_NOT_FREE_TEXT, "total", "integer from the envelope")]

    @computed_field  # type: ignore[prop-decorator]
    @property
    def showing(
        self,
    ) -> Annotated[
        int, Fenced(_NOT_FREE_TEXT, "showing", "integer derived from len(jobs)")
    ]:
        """How many jobs this result actually carries.

        Derived rather than stored, so it cannot disagree with `jobs`.
        The decision lives in the RETURN annotation because a computed
        field has no `FieldInfo.metadata` (R4-M1).
        """
        return len(self.jobs)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def summary(
        self,
    ) -> Annotated[
        str,
        Fenced(
            _NOT_FREE_TEXT,
            "summary",
            "derived by this server from two integers; no Jobvite content",
        ),
    ]:
        """The caller-facing `showing N of total` line.

        Derived from `showing` and `total` in one place, so the string
        a caller reads and the numbers beside it cannot drift
        (DESIGN.md:469-477).
        """
        return f"showing {self.showing:,} of {self.total:,}"
